// web/react/src/App.tsx
import { useState } from "react";
import { VerificationWidget } from "./VerificationWidget";
import type { WebSdkCompleteResult, WebSdkError, WebSdkEvent } from "./legitimuz";

// Vem do seu backend, em entry.url. Nunca commite um valor real.
const sdkUrl = import.meta.env.VITE_LEGITIMUZ_SDK_URL as string;

export default function App() {
  const [status, setStatus] = useState("montando");
  const [log, setLog] = useState<string[]>([]);
  const append = (line: string) => setLog((entries) => [...entries, line]);

  return (
    <>
      <VerificationWidget
        sdkUrl={sdkUrl}
        onReady={() => setStatus("pronto")}
        onEvent={(event: WebSdkEvent) => append(event.type)}
        // "terminou", não "aprovado": status é "submitted" ou "abandoned"
        onComplete={(result: WebSdkCompleteResult) => setStatus(`fim: ${result.status}`)}
        onCancel={() => setStatus("cancelado")}
        onError={(error: WebSdkError) => setStatus(`erro ${error.code}`)}
      />
      <p>{status}</p>
      <ul>
        {log.map((entry, i) => (
          <li key={i}>{entry}</li>
        ))}
      </ul>
    </>
  );
}

// web/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { VerificationWidgetComponent } from "./verification-widget.component";
import { environment } from "../environments/environment";
import type { WebSdkCompleteResult, WebSdkError, WebSdkEvent } from "./legitimuz";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [VerificationWidgetComponent],
  template: `
    <app-verification-widget
      [sdkUrl]="sdkUrl"
      (ready)="status = 'pronto'"
      (event)="onEvent($event)"
      (complete)="onComplete($event)"
      (cancel)="status = 'cancelado'"
      (error)="onError($event)"
    ></app-verification-widget>

    <p>{{ status }}</p>
    <ul>
      @for (entry of log; track $index) {
        <li>{{ entry }}</li>
      }
    </ul>
  `,
})
export class AppComponent {
  sdkUrl = environment.sdkUrl;
  status = "montando";
  log: string[] = [];

  onEvent(e: WebSdkEvent) {
    this.log.push(e.type);
  }

  // "o fluxo terminou", não "deu certo": status é "submitted" ou "abandoned"
  onComplete(r: WebSdkCompleteResult) {
    this.status = `fim: ${r.status}`;
  }

  onError(e: WebSdkError) {
    this.status = `erro ${e.code}`;
    this.log.push(e.user_message);
  }
}
